baseURL = 'https://travisjeffery.com/'
languageCode = 'en-us'
title = 'travis jeffery'

outputs = { home = ["HTML", "RSS", "JSON"] }

[permalinks]
  [permalinks.page]
    posts = "/:title/"

[params]
  description = "Hacker, writer, good guy."
  author = "Travis Jeffery"
  email = "tj@travisjeffery.com"
  url = "https://travisjeffery.com"

[markup]
  [markup.highlight]
    style = "github"

[markup.goldmark.renderer]
  unsafe = true
